version: "3.9"

services:
  app_api:
    build: .
    container_name: app_api
    command: ["python3", "app_api.py"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  streamlit_app:
    build: .
    container_name: streamlit_app
    command: ["streamlit", "run", "streamlit_app.py", "--server.address=0.0.0.0"]
    ports:
      - "8501:8501"
    volumes:
      - .:/app
